services:
  api:
    build: 
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=eventos
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./deployment/migrations:/docker-entrypoint-initdb.d/  

volumes:
  db_data:
